### ISSUE TITLE
Installing from npm

### ISSUE THREAD

**Issue by sholtomaud** [KoryNunn/modal-component#2]
What's the procedure to use npm to install this as a fastn component?

Is it:
1. npm i modal-component -g
2. manually pull out modalComponent.js
3. put modalComponent.js in fastn folder
4. require component in ...

```
module.exports = require('fastn')({
    _generic: require('fastn/genericComponent'),
    templater: require('fastn/templaterComponent'),
    list: require('fastn/listComponent'),
    text: require('fastn/textComponent'),
    modal: require('./components/modal')
}, true);
```

**Comment by KoryNunn** [comment]
Usage is listed in the readme, here: https://github.com/KoryNunn/modal-component/blob/master/README.md#fastn-component

**Comment by sholtomaud** [comment]
Oh, that's cool! 

So if I do a `npm i modal-component --save` I can just do `require('modal-component/modalComponent')` in the fastn/index.js file! Nice :+1:

**Comment by KoryNunn** [comment]
Yep, you can require any module in a package using that syntax.

**Comment by sholtomaud** [comment]
And this would be a requirebin example using fastn.

http://requirebin.com/?gist=c549c3abcae9c967d271
